name: Algolia Push (ZH)
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
env:
  ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
  ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
  ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
  HEXO_ALGOLIA_INDEXING_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
jobs:
  pushsearch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "latest"

      - name: Install & Push Algolia
        run: >
          npm install -D && npm install -g hexo-cli && npm run buildzh && hexo swpp && hexo algolia