name: Algolia Push
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
env:
  ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID_EN }}
  ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY_EN }}
  ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY_EN }}
  HEXO_ALGOLIA_INDEXING_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY_EN }}
jobs:
  pushsearch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install & Push Algolia
        run: >
          npm install -D && npm install -g hexo-cli && hexo clean && hexo generate && hexo bangumi -u && hexo algolia